# Generated by Django 4.1.3 on 2023-01-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
