# Generated by Django 4.1.3 on 2023-01-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
    ]
